server:
  error:
    include-stacktrace: never

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HelloWebFlux

    web:
      pageable:
        max-page-size: 100
        default-page-size: 20

logging:
  level:
    com:
      gui9394: DEBUG
    org:
      springframework:
        data:
          mongodb: DEBUG
