server:
  error:
    include-stacktrace: never

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HelloWebFlux

logging:
  level:
    com:
      gui9394: DEBUG
    org:
      springframework:
        data:
          mongodb: DEBUG
